name:                kasdown
version:             0.1.0.0
github:              "smallhadroncollider/kasdown"
license:             BSD3
author:              "Small Hadron Collider / Mark Wales"
maintainer:          "mark@smallhadroncollider.com"
copyright:           "Small Hadron Collider / Mark Wales"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smallhadroncollider/kasdown#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

library:
  source-dirs: src
  dependencies:
  - ansi-terminal
  - cmark-gfm
  - directory
  - file-embed
  - http-types
  - network-info
  - text
  - wai
  - warp

executables:
  kasdown:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kasdown


tests:
  kasdown-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kasdown
